export const SET_SWIPERS = 'SET_SWIPERS'

export const SET_NAVS = 'SET_NAVS'

export const SET_PRODUCTS = 'SET_PRODUCTS'

export const SET_RECOMMEND = 'SET_RECOMMEND'

export const SET_CATEGORYMENU = 'SET_CATEGORYMENU'

export const UPDATE_CATEGORYMENU_SELECT = 'UPDATE_CATEGORYMENU_SELECT'

export const SET_CATEGORYSHOW = 'SET_CATEGORYSHOW'

export const SET_GOODSDETAILS = 'SET_GOODSDETAILS'

export const SET_GOODSSPEC = 'SET_GOODSSPEC'

export const SET_HOTWORDS = 'SET_HOTWORDS'

export const ADD_LATELYWORDS = 'ADD_LATELYWORDS'

export const DEL_LATELYWORDS = 'DEL_LATELYWORDS'

export const SET_SEARCHPARAMS = 'SET_SEARCHPARAMS'

export const UPDATE_SEARCHPARAMS_ISHIDE = 'UPDATE_SEARCHPARAMS_ISHIDE'

export const UPDATE_SEARCHPARAMS_MULTIPLESELECT = 'UPDATE_SEARCHPARAMS_MULTIPLESELECT'

export const CANCEL_ALL_SEARCHPARAMS_SELECT = 'CANCEL_ALL_SEARCHPARAMS_SELECT'

export const SET_SERACHRESULT = 'SET_SERACHRESULT'

export const APPEND_SERACHRESULT = 'APPEND_SERACHRESULT'

export const SET_PAGEINFO = 'SET_PAGEINFO'

export const SET_GOODSCOMMENT = 'SET_GOODSCOMMENT'

export const APPEND_GOODSCOMMENT = 'APPEND_GOODSCOMMENT'

export const SET_LOGININFO = 'SET_LOGININFO'

export const CLEAR_LOGININFO = 'CLEAR_LOGININFO'

export const SET_USERINFO = 'SET_USERINFO'

export const SET_AVATARINFO = 'SET_AVATARINFO'

export const SET_MYFAVORITE = 'SET_MYFAVORITE'

export const APPEND_MYFAVORITE = 'APPEND_MYFAVORITE'

export const DELETE_MYFAVORITE = 'DELETE_MYFAVORITE'

export const SET_ADDRESSALL = 'SET_ADDRESSALL'

export const SET_ORDERALL = 'SET_ORDERALL'

export const APPEND_ORDERALL = 'APPEND_ORDERALL'

export const SET_ORDERREVIEW = 'SET_ORDERREVIEW'

export const APPEND_ORDERREVIEW = 'APPEND_ORDERREVIEW'

export const SET_ORDERDETAILS = 'SET_ORDERDETAILS'

export const SET_COMMENTITEM = 'SET_COMMENTITEM'

export const ADD_CARTGOODS = 'ADD_CARTGOODS'